// <auto-generated />
namespace Caritas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class First3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First3));
        
        string IMigrationMetadata.Id
        {
            get { return "201410032115522_First3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
